version: "3.8"
services:
  client:
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    container_name: client-container
    env_file:
      - ./client/.env.local
    networks:
      - travelago-network
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
  server:
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    container_name: server-container
    env_file:
      - ./server/.env
    networks:
      - travelago-network
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - travelago-network
    volumes:
      - dbData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=travelago
networks:
  travelago-network:
    driver: bridge
volumes:
  dbData:
  node_modules:
  web-root:
    driver: local
